AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Build PIP packages for AWS Lambda on AWS Lambda

Parameters:
  NewBucketName:
    Type: String
    Default: 'my-unique-bucket-name-8568324'
    Description: >
      The name of the new bucket which will be created. Must be a valid bucket name and unique in the AWS Universe.
      After the pip packages are built, they will be placed in this bucket
Resources:
  BuildFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: lambda_function.lambda_handler
      CodeUri: ./lambda_contents
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          TARGET_BUCKET:
            Ref: NewBucketName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: # TODO restrict to only actions and buckets as required (write)
                - 's3:*'
              Resource: !Sub 'arn:aws:s3:::${NewBucketName}*'
  TargetBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        Ref: NewBucketName

